### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by chase** [andreaslarsen/mono16#1]
First of all, thanks for putting time into this font! I've been looking for something like this for the past month or so.
In the meantime Input has been my goto font, but certain characters appear too wispy even with automatic hinting and it kind of irks me.

Anyway, I was wondering: do you plan on adding an opensource license to Mono16 in order to allow contributions and modifications?
My personal preference for licenses are:

[**MIT License**](https://tldrlegal.com/license/mit-license)
 * Not often used for fonts, but fonts are still software
 * Compatible with many other software licenses
 * About the only thing contributions and modifications can't do is change the copyright
 * About the closest thing you can get to the public domain while retaining copyright

[**SIL Open Font License**](https://tldrlegal.com/license/open-font-license-(ofl)-explained)
 * A bit more limiting than MIT, but more font-oriented
 * Prohibits the use of the original font name in forks
 * Prohibits re-licensing
 * Prohibits commercial sale when not packaged with other software
 * Allows you to sell font design services, so a Patreon or similar is still permitted

I'd like to eventually make a couple of additions, such as box drawing, geometric characters, and Powerline symbols as well as maintain a personal fork with a slashed zero and regular asterisk.

**Comment by andreaslarsen** [comment]
Great - if you look at the font file it's already OFL (I'll add License.txt) so by all means modify and pull back :smile:

**Comment by andreaslarsen** [comment]
And I'm drawing an improved zero right now and will be adding dotless and slashed variants too 

(I don't like to use the slashed myself since it looks like Ø to me)

**Comment by andreaslarsen** [comment]
And the regular asterisk is already in the font - opentype style set 1 which can be "flattened" using e.g. font squirrels font generator

**Comment by chase** [comment]
Fantastic, thanks for letting me know! Indeed, I didn't notice &mdash; Fontforge and I aren't on the best of terms right now, haha.

I don't often encounter Norwegian or Danish in code, but I can totally understand why that could be an issue. Never really noticed that until you pointed it out!

Simple Terminal by Suckless isn't too fond of fontconfig or freetype for that matter, so manually copying and pasting the asterisk glyph would probably end up being simpler for me, haha.

**Comment by andreaslarsen** [comment]
Ok, I can upload source as UFO if you want

**Comment by chase** [comment]
No need, thank you! The sfdirs should be fine for what I plan on adding.
