### ISSUE TITLE
Upload better screenshots for showcasing the font

### ISSUE THREAD

**Issue by vinitkumar** [andreaslarsen/mono16#3]
Hey @andreaslarsen. Sorry for opening an issue like this. But I feel the current screenshot that you have upload to the website doesn't really do justice to the font. You have a very narrow width for content and even the screenshots looks bit pushed from both side. It would really be more presentable and attractive if you could please add better screenshot and increase the width for content. 

Thanks for reading this.

Cheers!
Vinit

**Comment by andreaslarsen** [comment]
Hello, I'm not sure what screenshots you're referring to?

**Comment by vinitkumar** [comment]
@andreaslarsen Sorry for not being very clear about it. assumed wrongly
![screen shot 2015-04-05 at 3 36 35 pm](https://cloud.githubusercontent.com/assets/537678/6996507/988e14f4-dba9-11e4-8d16-f159ce535c4c.png)
  that this was an image.  I was feeling that the current layout was not doing justice to the font and uploading a high quality screenshot on an editor like this would encourage more people to use thsi font. ![Screenshot](https://camo.githubusercontent.com/02f2bfac13de41eca2f7b8829321747a34087a26/68747470733a2f2f636c6475702e636f6d2f31646d4a496c5f514b562d3330303078333030302e706e67)

Thanks for the font. :+1:

**Comment by andreaslarsen** [comment]
No worries, I think I'll stick to what I have since it allows people to edit and change color schemes on the website.
