### ISSUE TITLE
Enable slashed zero in Windows

### ISSUE THREAD

**Issue by trdunsworth** [andreaslarsen/mono16#8]
Love the look of this. Want to know how I can change my defaults to have a slashed zero rather than dotted. While I love fonts, how to enable various permutations has always been just outside my reach.

**Comment by andreaslarsen** [comment]
did you read the guide linked to from the webpage?

**Comment by andreaslarsen** [comment]
I know downloading -> uploading -> download isn't ideal but that's the easiest way right now until #2 happens :)

**Comment by trdunsworth** [comment]
I had clicked on it, but Chrome gave me the raw html instead of the pdf. I found the guide on the site here and followed it. So that solved my issues perfectly. 

Thank you much for getting back to me! :-)

**Comment by andreaslarsen** [comment]
:+1: could you try and see if this link to the pdf works? https://github.com/andreaslarsen/mono16/raw/master/Resources/Readme.pdf?raw=true

**Comment by trdunsworth** [comment]
That worked perfectly! Very nice! And the font looks great with the slashed zero

**Comment by andreaslarsen** [comment]
I know I should probably set the slashed zero as default - I will probably make a survey once the font is more complete and ask people what they prefer as defaults (also for e.g. i,j,l,$).

I prefer the dotted one since I'm danish and we have the Øø letter...a greek person would probably prefer dotted since the have the Θ letter.

**Comment by trdunsworth** [comment]
I can understand the rationale behind the preference. I actually write a slashed zero when I'm writing things out by hand as well, but were I able to speak Danish, I would likely have the same preference. Have you seen the Input font. It's also highly customizable and is very interesting. What I like about your font is the narrow width personally. That makes it more comforting for me because it's closer to my own handwriting.

**Comment by andreaslarsen** [comment]
I've been using it as system font since it came;)

I've never used it for coding though as I like narrower fonts too...been using pragmata pro and m+ but both had issues and didn't have that bitmap like sharpness on my trusty old 15 lo-res mbp.

**Comment by trdunsworth** [comment]
I've used it in coding for a while now, mainly because I could customize it as much as I wanted. I couldn't afford Pragmata Pro as much as I love the look of it. I tried m+, but it just really didn't work for me. So this is a great option for a narrow font, I can afford and if I can help in any way, I'm all ears.

**Comment by andreaslarsen** [comment]
thanks, I don't have anything specific right now but feel free to improve it in whatever way you like. I'll add  the "Help Wanted" label to issues where I could use some help.
